### PR TITLE
Tranporter inhibitor

### PR DESCRIPTION
**Pull request by Jarkyc**
**Transporter Inhibitor:**
- Built into STM: Transporters
- Spawnable entity
- Able to be destroyed via shooting
- Health and Radius can be set via the properties menu
- Temporary model until one is made
- Temporary on / off state colors only show for the person who spawned it in

### CODE REVIEW

**Comment by Jarkyc** [comment]
Don't merge this until I push another commit. I don't like the way the activation display is rn

**Comment by Jarkyc** [comment]
Help, I am a lonely pull request! Please look at me!

**Comment by oninoni** [comment]
Error when pressing E on inhibitor:

[stm_transporter] addons/stm_transporter/lua/star_trek/inhibitor_entity/entities/inhibitor_entity/init.lua:68: bad argument #1 to 'insert' (table expected, got nil)
  1. insert - [C]:-1
   2. unknown - addons/stm_transporter/lua/star_trek/inhibitor_entity/entities/inhibitor_entity/init.lua:68


[stm_transporter] lua/includes/extensions/table.lua:656: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. KeyFromValue - lua/includes/extensions/table.lua:656
    3. RemoveByValue - lua/includes/extensions/table.lua:663
     4. unknown - addons/stm_transporter/lua/star_trek/inhibitor_entity/entities/inhibitor_entity/init.lua:74

**Comment by Jarkyc** [comment]
Fixed + Added copyright banners + If you look at the entity and you are the owner it now shows you the radius

**Pull request merged**
